import { Injectable } from '@angular/core';
import {Esencias, Magia} from "../../../../../shared/interface/interface-armado";
import {ArmadoTresService} from "../../../service/armado-tres.service";

@Injectable({
  providedIn: 'root'
})
export class MagiasSelectService {
  private magias: Magia[] = [
    {
      titulo: "",
      nombre: "Mitigar",
      skillId: 1,
      esenciaId:1,
      siglasEsencia: 'FOR',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Robustez",
      skillId: 2,
      esenciaId:1,
      siglasEsencia: 'FOR',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Coraza",
      skillId: 3,
      esenciaId:1,
      siglasEsencia: 'FOR',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Espíritu Férreo",
      skillId: 4,
      esenciaId:1,
      siglasEsencia: 'FOR',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Guardaespaldas",
      skillId: 5,
      esenciaId:1,
      siglasEsencia: 'FOR',
      puntos: 0,
    },

    {
      titulo: '',
      nombre: "Amplificador de fuerzas",
      skillId: 1,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Cobertura",
      skillId: 2,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Impulso",
      skillId: 3,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Curación",
      skillId: 4,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Manto místico",
      skillId: 5,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Marca del Condenado",
      skillId: 6,
      esenciaId:2,
      siglasEsencia: 'APO',
      puntos: 0,
    },

    {
      titulo: '',
      nombre: "Atadura",
      skillId: 1,
      esenciaId:3,
      siglasEsencia: 'CON',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Silencio",
      skillId: 2,
      esenciaId:3,
      siglasEsencia: 'CON',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Cegar",
      skillId: 3,
      esenciaId:3,
      siglasEsencia: 'CON',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Dormir",
      skillId: 4,
      esenciaId:3,
      siglasEsencia: 'CON',
      puntos: 0,
    },
    {
      titulo: '',
      nombre: "Marcha en trance",
      skillId: 5,
      esenciaId:3,
      siglasEsencia: 'CON',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Armamento óseo",
      skillId: 1,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Coraza ósea",
      skillId: 2,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Escamas Cenizas",
      skillId: 3,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Moldeo del Elemento propio",
      skillId: 4,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Extender",
      skillId: 5,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Manipular el elemento muerto",
      skillId: 6,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Reflejos eléctricos",
      skillId: 7,
      esenciaId:4,
      siglasEsencia: 'CUE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Potenciar el envase",
      skillId: 1,
      esenciaId:5,
      siglasEsencia: 'DAÑ',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Energía mágica",
      skillId: 2,
      esenciaId:5,
      siglasEsencia: 'DAÑ',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Explosión",
      skillId: 3,
      esenciaId:5,
      siglasEsencia: 'DAÑ',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Toxina",
      skillId: 4,
      esenciaId:5,
      siglasEsencia: 'DAÑ',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Arma guía",
      skillId: 5,
      esenciaId:5,
      siglasEsencia: 'DAÑ',
      puntos: 0,
    },

    {
      titulo: "",
      nombre: "Habilidad Elemental – Elementum",
      skillId: 1,
      esenciaId:6,
      siglasEsencia: 'ELE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Paso elemental",
      skillId: 2,
      esenciaId:6,
      siglasEsencia: 'ELE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Piel del elemento",
      skillId: 3,
      esenciaId:6,
      siglasEsencia: 'ELE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Comer elemento",
      skillId: 4,
      esenciaId:6,
      siglasEsencia: 'ELE',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Armamento",
      skillId: 1,
      esenciaId:7,
      siglasEsencia: 'INV',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Encantamiento de equipamiento",
      skillId: 2,
      esenciaId:7,
      siglasEsencia: 'INV',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Invocación efímera",
      skillId: 3,
      esenciaId:7,
      siglasEsencia: 'INV',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Llamar",
      skillId: 4,
      esenciaId:7,
      siglasEsencia: 'INV',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Lenguas del placer",
      skillId: 1,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Telequinesis",
      skillId: 2,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Ojos del miedo",
      skillId: 3,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Ojos que no ven",
      skillId: 4,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Nulo",
      skillId: 5,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Comunicación mental",
      skillId: 6,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Cuidador de secretos",
      skillId: 7,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Lectura",
      skillId: 8,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Mas allá",
      skillId: 9,
      esenciaId:8,
      siglasEsencia: 'MEN',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Fuego reducido",
      skillId: 1,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Oculto",
      skillId: 2,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Salto",
      skillId: 3,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Sed de vida",
      skillId: 4,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Rastrear lo arcano",
      skillId: 5,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Percibir la magia",
      skillId: 6,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Lengua astuta",
      skillId: 7,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },
    {
      titulo: "",
      nombre: "Ecos",
      skillId: 8,
      esenciaId:9,
      siglasEsencia: 'SAG',
      puntos: 0,
    },

  ];
  public esencias: Esencias[];
  constructor(
    public armadotresService: ArmadoTresService
  ) {
    this.esencias = this.armadotresService.prEsencias
  }
  getMagias(): Magia[] {
    return this.magias;
  }
  getEsencias(): Esencias[]{
    return this.esencias;
  }
}
