import { Injectable } from '@angular/core';
import {Estadistica, HabilidadSelect} from "../../../../../../shared/interface/interface-armado";
import {ArmadoDosService} from "../../../../service/armado-dos.service";
@Injectable({
  providedIn: 'root'
})
export class HabilidadesSelectService {
  private habilidades: HabilidadSelect[] = [
    {
      titulo: "Utilizar armas mágicas y efectos.",
      nombre: "Armas mágicas",
      skillId: 1,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Regenera usos de una Magia.",
      nombre: "Meditacion",
      skillId: 2,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Forma de percibir la magia.",
      nombre: "Ocultismo",
      skillId: 3,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Crear elixires/Pociones.",
      nombre: "Pociones",
      skillId: 4,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Bloquea Ataques Magicos.",
      nombre: "resistencia mágica",
      skillId: 5,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Realizar rituales y canalizarlos.",
      nombre: "Rituales",
      skillId: 6,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Capacidad de leer y escribir Runas.",
      nombre: "Rúnico",
      skillId: 7,
      statId:1,
      siglasStat: 'ARC',
      puntos: 0,
    },
    {
      titulo: "Percibir el entorno y adelantarse a un suceso.",
      nombre: "Alerta",
      skillId: 1,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Dar funcionalidad a ciertos elementos del entorno.",
      nombre: "Armamento improvisado",
      skillId: 2,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Saber manejarse en el submundo de las ciudades.",
      nombre: "Callejeo",
      skillId: 3,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Realizar intercambios, transacciones o negociar correctamente.",
      nombre: "Finanzas",
      skillId: 4,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Capacidad de robar sin que se percaten de ello.",
      nombre: "Latrocinio",
      skillId: 5,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Capacidad de engañar a uno o más objetivos.",
      nombre: "Mentir",
      skillId: 6,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Apuntar a un objetivo.",
      nombre: "Puntería",
      skillId: 7,
      statId:2,
      siglasStat: 'AST',
      puntos: 0,
    },
    {
      titulo: "Mediar en un conflicto para llegar a una rápida y pacífica solución.",
      nombre: "Diplomacia",
      skillId: 1,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Poder ponerse en la situación emocional de otra persona.",
      nombre: "Empatía",
      skillId: 2,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Relacionarse de forma educada, cómo comportarse, como vestir y como actuar.",
      nombre: "Etiqueta",
      skillId: 3,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Imponerse ante otros atraves del miedo.",
      nombre: "Intimidación",
      skillId: 4,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Dar órdenes a un grupo de personas y motivarlas para alcanzar una meta.",
      nombre: "Liderazgo",
      skillId: 5,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Hacer que alguien realise determina accion atraves de chantajes.",
      nombre: "Manipulación",
      skillId: 6,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "Hacer que alguien realise determina accion atraves del encanto y la razon.",
      nombre: "Persuasión",
      skillId: 7,
      statId:3,
      siglasStat: 'CAR',
      puntos: 0,
    },
    {
      titulo: "El uso de armas que disparen algún proyectil.",
      nombre: "Armas de disparo",
      skillId: 1,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Permite arrojar objetos con precisión.",
      nombre: "Arrojar",
      skillId: 2,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Capacidad física de realizar proezas en terreno difícil sin caerse.",
      nombre: "Equilibrio",
      skillId: 3,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Capacidad fisica de evadir/evitar el ataque contrario",
      nombre: "Esquivar",
      skillId: 4,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Realizar tareas de precisión y motricidad fina.",
      nombre: "Manualidades",
      skillId: 5,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Poder montar y dirigir a un animal.",
      nombre: "Montar",
      skillId: 6,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Permite realizar acciones sin ser detectado.",
      nombre: "Sigilo",
      skillId: 7,
      statId:4,
      siglasStat: 'DES',
      puntos: 0,
    },
    {
      titulo: "Saltar, correr, trepar, nadar, entre otros.",
      nombre: "Atletismo",
      skillId: 1,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Uso de armas chicas, faciles de ocultar y manejar.",
      nombre: "Armas ligeras",
      skillId: 2,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Uso de armas que requieren de una mano o las dos.",
      nombre: "Armas medias",
      skillId: 3,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Uso de armas que requieren de dos manos.",
      nombre: "Armas pesadas",
      skillId: 4,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Correr y aplicar fuerza contra un objetivo.",
      nombre: "Cargar",
      skillId: 5,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Aplicar fuerza sobre un objetivo para desplazarlo de su posición original.",
      nombre: "Empuje",
      skillId: 6,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Poder aplicar diferentes golpes o técnicas de combate.",
      nombre: "Pelea",
      skillId: 7,
      statId:5,
      siglasStat: 'FUE',
      puntos: 0,
    },
    {
      titulo: "Conceptos básicos de estudio, leer, escribir y matemáticas básicas.",
      nombre: "Academicismo",
      skillId: 1,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Poder recrear en papel un mapa que represente un sector geográfico.",
      nombre: "Cartografía",
      skillId: 2,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Dirigir vehículos tirados por animales o por vapor.",
      nombre: "Conducir",
      skillId: 3,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Capacidad de poder comprender, hablar, escuchar, leer y escribir otros idiomas.",
      nombre: "Idiomas",
      skillId: 4,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Concentrarse en buscar un objetivo en específico.",
      nombre: "Investigación",
      skillId: 5,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Necesaria para aplicar conocimientos médicos.",
      nombre: "Medicina",
      skillId: 6,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Capacidad de poder reconocer y poder crear diferentes tipos de música.",
      nombre: "Música",
      skillId: 7,
      statId:6,
      siglasStat: 'INT',
      puntos: 0,
    },
    {
      titulo: "Continuar con cansancio, hambre o herido.",
      nombre: "Aguante",
      skillId: 1,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "Agarres fisicos con el fin de inmovilizar al objetivo.",
      nombre: "Apresar",
      skillId: 2,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "Absorber un impacto sin recibir o reducir el daño.",
      nombre: "Bloqueo",
      skillId: 3,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "El uso de ropaje pesado y no verse interferido por el peso.",
      nombre: "Equipamiento pesado",
      skillId: 4,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "Capacidad de aguantar en una posición o lugar, derribos y ciertos controles de masa.",
      nombre: "Firmeza",
      skillId: 5,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "Recuperar el ritmo cuando se está cansado y renovar las fuerzas.",
      nombre: "Recuperación",
      skillId: 6,
      statId:7,
      siglasStat: 'RES',
      puntos: 0,
    },
    {
      titulo: "Permite a los personajes poder leer una situación o descifrar el ambiente.",
      nombre: "Interpretación",
      skillId: 1,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Reconocer los elementos del ambiente natural.",
      nombre: "Naturaleza",
      skillId: 2,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Reconocer el terreno, futuros eventos o la veracidad de una frase.",
      nombre: "Percepción",
      skillId: 3,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Restaurar Objetos.",
      nombre: "Reparaciones",
      skillId: 4,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Orientarse, refugiarse, alimentarse, sobrevivir en intemperie.",
      nombre: "Supervivencia",
      skillId: 5,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Conocimiento sobre los diferentes dioses,credos y el estudio de estos.",
      nombre: "Teología",
      skillId: 6,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Entablar relación estrecha y allegados con los animales.",
      nombre: "Trato con Animales",
      skillId: 7,
      statId:8,
      siglasStat: 'SAB',
      puntos: 0,
    },
    {
      titulo: "Poder controlarse ante situaciones adbersas y mantener la calma.",
      nombre: "Autocontrol",
      skillId: 1,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },
    {
      titulo: "Mantener el enfoque en la tarea que se esta haciendo.",
      nombre: "Concentración",
      skillId: 2,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },
    {
      titulo: "Mantener una decision, idea o meta, para continuar hacia su objetivo.",
      nombre: "Convicción",
      skillId: 3,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },
    {
      titulo: "statId para realizar ciertas proezas.",
      nombre: "Coraje",
      skillId: 4,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },
    {
      titulo: "Tener un presentimiento o sensación extra a la de sus sentidos.",
      nombre: "Instintos",
      skillId: 5,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },
    {
      titulo: "Resistir hechizos de control que impidan el lanzamiento de habilidadesid o desplazamiento.",
      nombre: "Tenacidad",
      skillId: 6,
      statId:9,
      siglasStat: 'VOL',
      puntos: 0,
    },


  ];
  public estadisticas: Estadistica[];
  constructor(
    public armadoDosService: ArmadoDosService
  ) {
    this.estadisticas = this.armadoDosService.prEtadisticas
  }

  getHabilidades(): HabilidadSelect[] {
    return this.habilidades;
  }
  getEstadisticas(): Estadistica[]{
    return this.estadisticas;
  }
}
